name: Image Resizer Action

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  image_resize_job:
    name: Image Resize Job
    runs-on: ubuntu-latest
    steps:
     - name: checkout
       uses: actions/checkout@v4
     - name: Install ImageMagick
       run: sudo apt install libvips-tools
     - name: resize jpeg images
       run:  vipsthumbnail ./images/*.jpeg --size 1300x2600 -o $(readlink -f "./new_images/%s.jpeg")
     - name: Commit
       run: |
        git add -A
        git commit -m "adding resized photos"
        git push
